### ISSUE TITLE
数据库文件嗯

### ISSUE THREAD

**Issue by Chenjiehan1994** [yuanguangxin/Questionnaire#1]
如题

**Comment by yuanguangxin** [comment]
和Model实体类一一对应的，具体邮箱给你发了一份

**Comment by StringKe** [comment]
求发一份谢谢

**Comment by yuanguangxin** [comment]
按model建吧 跟model一样的 时间太长了找不到了

发自我的 iPhone

**Comment by StringKe** [comment]
> 按model建吧 跟model一样的 时间太长了找不到了 发自我的 iPhone
> […](#)
> 在 2018年12月13日，17:32，StringKe ***@***.***> 写道： 求发一份谢谢 — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or mute the thread.

ok,谢谢,项目二改可能商用需要授权么?

**Comment by yuanguangxin** [comment]
不用

发自我的 iPhone
